rust-cli/human-panic

- src/lib.rs
- src/report.rs
🐛 bug fix
During trying human-panic, the current path caught my eye: `/var/folders/zw/bpfvmq390lv2c6gn_6byyv0w0000gn/T//report-9f934660-cf8f-418c-be89-c99728664a46.toml`. There's a double "//" in there, which usually indicates that you are joining paths using `format!` instead of properly using the path API. This change makes human-panic use the path API.
To the extend they passed before, `examples/err.rs` is broken.
path version bump, I consider this a bugfix.
> Properly handle file paths using Path and PathBuf

- src/lib.rs
- src/report.rs
This a 🐛 bug fix.
Currently this is what the crash dump looked for a tool I wanted to use `human-panic` in:
```
name = "human-panic"
operating_system = "unix:Unknown"
crate_version = "0.2.0"
explanation = "Panic occurred in file 'libcore/option.rs' at line 335\n"
method = "Panic"
```
This change (using the Metadata object we pass around anyways) fixes this problem
> Fixing wrong data in certain crash dump fields

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/report.rs
**Choose one:** is this a 🙋 feature
This PR adds a full backtrace of the application to the `dump.toml` files. This adds the `backtrace` dependency
```
spacekookie@azedes ~/P/human-panic> cat /tmp/report-fb71d719-7826-48d5-a0c2-376f6dd62725.toml                                                                                                                21:32:10
name = 'human-panic'
operating_system = 'unix:Unknown'
crate_version = '0.2.0'
explanation = '''
Cause: OMG EVERYTHING IS ON FIRE!!!. Panic occurred in file 'examples/panic.rs' at line 8
'''
method = 'Panic'
backtrace = '''
stack backtrace:
0:     0x55968f4db994 - backtrace::backtrace::libunwind::trace::h69e50feca54bfb84
at /home/spacekookie/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.6/src/backtrace/libunwind.rs …
```
> Adding proper backtraces to the dump files

- src/lib.rs
**Choose one:** is this a 🐛 bug fix
There was a bug in the formatting of the authors list
Bump patch
> Fixing the formatting for authors from ':' to ', ' as a seperator

- src/lib.rs
- src/report.rs
**Choose one:** 🐛 bug fix
Now when we fail to write the dump to disk, `human-panic` will no longer panic!
Issue: #12
> Fixing double panic

- Cargo.toml
- src/lib.rs
- tests/custom-panic/Cargo.toml
- tests/custom-panic/src/main.rs
- tests/custom-panic/tests/integration.rs
**Choose one:** This is a 🙋 feature
Adds a second macro end-point for users to use the Metadata struct to provide their own data, overriding the defaults chosen by Cargo.
This depends on #33
> Adding a second endpoint for setup_panic!

- src/lib.rs
By not refering to the name of the crate directly, it us now possible
to re-export and use `setup_panic!` in quicli.
This a somewhat of a 🐛 bug fix, but also a new 🙋 feature.
I want to use this in quicli
Patch version bump is enough.
> Don't require users to have extern crate

- .gitignore
- README.md
- src/lib.rs
The docs refer to catch_unwind while this library actually uses set_hook. Looks like it used to use catch_unwind and was never changed.
By removing the / at the end of target then .gitignore will handle both folders and symlinks.
This is useful as I symlink my target directories to make syncing projects between machines faster.
This is mostly a 🔦 documentation change
patch version
> docs + .gitignore fix

- .travis.yml
- src/lib.rs
This a 🐛 bug fix.
The clippy-preview works on the stable channel now so we can pin it on 1.29.1 and use it for lints and formatting without having to bump clippy and or nightly every so often.
> Pinning clippy on 1.29.1 stable to avoid more uneccesary CI breakage

- src/lib.rs
- src/report.rs
**Choose one:** This a 🐛 bug fix
Including original panic-cause in report
Okay so this PR is a bit of a dilemma.
The API we need to get the original panic message isn't stable
and requires a feature flag.
We can conditionally enable the feature flag for nightly users
but that doesn't quite deal with the problem of what to do
when someone is using `human-panic` on stable.
As far as I can see there's no other API to get that information?
We could always just gate it all away behind the `nightly` feature
and just ommit a static "not supported" or something when running
on stable.
The tests pass (provided you pass `--features nightly` for now).
Wanted to open this PR to discuss how to proceed :)
This fixes #40
This should be a minor bump I believe?
The `Report` struct isn't exported so adding …
> Including original-sin (panic) in report

- src/lib.rs
- tests/custom-panic/tests/integration.rs
- tests/single-panic/tests/integration.rs
This is a 🙋 feature.
The general rationale for this is documented in #48.
This PR implements the required behaviour. A `human-panic`
message will only be displayed if two conditions are met
1. The program is **not** running in `DEBUG` mode
2. `RUST_BACKTRACE` is **not** set as an env variable
This PR also adjusts the tests to check for both present
and non-present `human-panic` messages. 
---
There are two things missing
- A test that checks for the `RUST_BACKTRACE` override
behaviour when running in `RELEASE` mode. This is currently
not easy to do with `assert_CLI` (there might be more PRs 🙂)
Now, this is a matter of how you _define_ a version breakage.
SemVer is ambigous when it comes to what is and isn't a breakage,
for example, if people are depending on human-panic messages to be …
> Only display message for humans (implementing #48)

- .travis.yml
This PR fixes #28. We don't currently verify `human-panic`
properly works anymore. So this adds running tests on the
oldest version we support (which is 1.25.*)
> Properly test code on oldest supported rust version

- Cargo.toml
- src/report.rs
human-panic was a major reason for dependencies with duplicate, outdated version, so I upgraded them.
**Choose one:** is this a 🐛 bug fix, a 🙋 feature, or a 🔦 documentation change? Well, I'd say  :memo: chore
afaik they are not part of the api so patch level
> Upgrade depencies

- src/report.rs
Closes  #52
Example of from `tests/` repo with debug symbols https://gist.github.com/DoumanAsh/4b1da5519a86df101e3a4f88f7e4d812
Let me know if changes to format needed, then I'll update examples in README.md
> Add custom backtrace printer that excludes frames outside of user's code

- src/lib.rs
- tests/custom-panic/src/main.rs
Cargo guidelines are to not set a homepage if it isn't any different
than the repository URL. This causes the report to not have any link
back to file an issue. If the repository is available, print it as well.
---
Note that I've tried to find a reference to the "don't set `homepage` if it isn't the same" guideline, but haven't found it yet.
The environment variable is not available yet. See https://github.com/rust-lang/cargo/pull/6096
**Choose one:** is this a 🙋 feature?
None
Major; the `Metadata` structure has a new field that isn't specified in existing code.
> metadata: add repository

- src/lib.rs
- src/report.rs
**Choose one:** 🙋 feature
Hi! 👋 I was wondering if you'd be opposed to the idea of exposing the `report` mod as public. It is pretty useful on its own and I intend to use the `Report` struct directly instead of printing the result.
No worries if you don't want to increase the API surface, though. :)
It changes the public interface, but in a backwards-compatible way. So minor bump should be fine.
> Make report mod public

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/report.rs
- tests/custom-panic/Cargo.toml
- tests/custom-panic/src/main.rs
- tests/custom-panic/tests/integration.rs
- tests/single-panic/Cargo.toml
- tests/single-panic/src/main.rs
- tests/single-panic/tests/integration.rs
Update the project to 2018 edition in both code and documentation for
usage, prunes unused dependencies and removes dependency on failure,
preferring the std Error trait.
There was also a misleading error message about not being able to find a
temporary file directory, which would have actually have been caused by
a failure to encode a filepath into UTF-8
(https://doc.rust-lang.org/src/std/path.rs.html#1848-1850). However this
error should not happen anyway by just using the PathBuf directly to
make the full path for the persisted file output.
Should resolve https://github.com/rust-cli/human-panic/issues/57
**Choose one:** is this a 🐛 bug fix, a 🙋 feature, or a 🔦 documentation change?
Feature and docs
https://github.com/rust-cli/human-panic/issues/57
Should take a minor bump potentially, …
> Update to 2018 edition and prune dependencies

- src/lib.rs
🐛 Set `cause`, whether we're on nightly or not.
Previously there were two cases with two sub-cases:
- if compiled with nightly:
- if there is a panic message: set it as `cause`
- if there is no panic message: set `cause` to "Unknown"
- if not compiled with nightly: set cause to "Error cause could not be determined by the application.", _and also:_
- if there is a panic message: attach it straight to the `expl` string as "Cause: <cause>."
That seems oddly complicated. This PR changes that to:
- if there is a panic message (no matter if we're on nightly or not): set it as `cause`
- if there is no panic message (no matter if we're on nightly or not): set `cause` to "Unknown"
Vaguely related to https://github.com/rust-cli/human-panic/issues/55.
This changes the format of the message users …
> Include cause, whether on nightly or not

- README.md
🔦 Fix Travis links in README badge - **[see preview](https://github.com/curiousleo/human-panic/blob/patch-1/README.md)**.
https://travis-ci.org/rust-clique/human-panic does not exist.
The correct link is https://travis-ci.org/rust-cli/human-panic.
Nope.
No release required.
> Change Travis links from rust-clique to rust-cli

- README.md
I just spent about twenty minutes debugging why human-panic wasn't working.
I hadn't enabled release mode and had no idea that release mode affected it.
This is a 🔦 documentation change.
N/A
None
> README: Clarify that release mode is needed in order to use human-panic

- Cargo.toml
- src/report.rs
It is a bit controversial, because I'm the maintainer of the `os_info` crate, but it can detect Windows, so `cfg!(windows)` is no longer needed. Additionally, this crate can obtain the Windows version and support more platforms.
N/A
Not sure.
The format of the `operating_system` field of the `Report` has changed, but I'm not sure if it is considered a part of the API.
> Use os_info instead of os_type

- CHANGELOG.md
- src/lib.rs
An indirect route to allowing custom paths, renderers, etc
Fixes #70
Fixes #69
Fixes #62
> feat: Expose machinery to customize `setup_panic!`

- src/lib.rs
I actually ran into this in the wild with a local `Metadata` struct that wasn't being referenced correctly in the outer function, resulting in pretty obvious compilation errors.
> Ensure macro-internal variables are properly encapsulated

- src/lib.rs
We can't properly fix this until our MSRV is bumped to 1.81
Fixes #159
> fix: Silence deprecation message
